import "./globals.css";

export const metadata = {
  title: "Vezir Oni",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-galanoRegular px-5 sm:px-0`}>{children}</body>
    </html>
  );
}
